// Code generated by "goaccessor --target bestSellingBook --field --getter --include author --prefix BestSelling". DO NOT EDIT.

package main

func GetBestSellingAuthor() string {
        return bestSellingBook.author
}
