// Code generated by "goaccessor --target bestSellingBook --field --getter --include Author --prefix BestSelling". DO NOT EDIT.

package main

func GetBestSellingAuthor() string {
        return bestSellingBook.Author
}
