// Code generated by "goaccessor --target Book --getter --setter". DO NOT EDIT.

package main

func (b *Book) GetTitle() string {
        return b.Title
}

func (b *Book) SetTitle(v string) {
        b.Title = v
}

func (b *Book) GetAuthor() string {
        return b.Author
}

func (b *Book) SetAuthor(v string) {
        b.Author = v
}
