// Code generated by "goaccessor --target Book --getter --setter". DO NOT EDIT.

package main

func (b *Book) GetTitle() string {
	return b.title
}

func (b *Book) SetTitle(v string) {
	b.title = v
}

func (b *Book) GetAuthor() string {
	return b.author
}

func (b *Book) SetAuthor(v string) {
	b.author = v
}
